# Generated by Django 4.2.2 on 2023-06-08 11:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EQTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(choices=[('а', 'а'), ('б', 'б'), ('в', 'в'), ('г', 'г'), ('д', 'д')], max_length=1, unique=True, verbose_name='Буква')),
            ],
        ),
        migrations.CreateModel(
            name='TestLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=10, verbose_name='Логин')),
            ],
        ),
        migrations.CreateModel(
            name='LetterEQTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=1, verbose_name='Порядковый номер')),
                ('eq_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.eqtest')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.letter')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='IQTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('point', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Меньше чем 0 не бывает!!'), django.core.validators.MaxValueValidator(50, 'Больше чем 50 не бывает!')], verbose_name='Баллы')),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iqtests', to='testing.testlogin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='eqtest',
            name='letters',
            field=models.ManyToManyField(through='testing.LetterEQTest', to='testing.letter'),
        ),
        migrations.AddField(
            model_name='eqtest',
            name='login',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eqtests', to='testing.testlogin'),
        ),
    ]
